# https://yaml.org/type/float.html
data:
  language: english
  raw_path: /mnt/mahaoxin/PaddleSpeechTask/data/english/LREC_converted  #path to raw dataset
  save_path: data/lrec  #path to save dataset
  glove_path: /mnt/mahaoxin/PaddleSpeechTask/data/english/glove.840B.300d.txt #glove embedding name
  glove_name: 840B
  vocab: data/lrec/vocab.json
  train_set: data/lrec/train.json
  dev_set: data/lrec/dev.json
  dev_text: /mnt/mahaoxin/PaddleSpeechTask/data/english/LREC_converted/dev.txt
  ref_set: data/lrec/ref.json
  ref_text: /mnt/mahaoxin/PaddleSpeechTask/data/english/LREC_converted/ref.txt
  asr_set: data/lrec/asr.json
  asr_text": /mnt/mahaoxin/PaddleSpeechTask/data/english/LREC_converted/asr.txt
  max_vocab_size: 50000
  max_sequence_len: 200
  min_word_count: 1
  min_char_count: 10
  use_pretrained: False
  
  pretrained_emb: data/lrec/glove_emb.npz

collator:
  mean_std_filepath: data/mean_std.json
  unit_type: char
  vocab_filepath: data/vocab.txt
  augmentation_config: conf/augmentation.json
  random_seed: 0
  spm_model_prefix: 
  specgram_type: linear
  feat_dim: 
  delta_delta: False
  stride_ms: 10.0
  window_ms: 20.0
  n_fft: None
  max_freq: None
  target_sample_rate: 16000
  use_dB_normalization: True
  target_dB: -20
  dither: 1.0
  keep_transcription_text: False
  sortagrad: True 
  shuffle_method: batch_shuffle
  num_workers: 0
  batch_size: 4
  
model:
  num_conv_layers: 2
  num_rnn_layers: 3
  rnn_layer_size: 2048
  use_gru: False 
  share_rnn_weights: True 

training:
  n_epoch: 24
  lr: 1e-5 
  lr_decay: 1.0 
  weight_decay: 1e-06
  global_grad_clip: 5.0
  log_interval: 1

decoding:
  batch_size: 128
  error_rate_type: wer
  decoding_method: ctc_beam_search
  lang_model_path: data/lm/common_crawl_00.prune01111.trie.klm
  alpha: 2.5
  beta: 0.3
  beam_size: 500
  cutoff_prob: 1.0
  cutoff_top_n: 40
  num_proc_bsearch: 8
