data:
  dataset_type: BertLine
  train_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/train
  dev_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/dev
  test_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/test2011
  data_params: 
    pretrained_token: bert-base-uncased  #english
    punc_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/english/data/iwslt2012_en/punc_vocab
    seq_len: 100
  batch_size: 32
  sortagrad: True 
  shuffle_method: batch_shuffle
  num_workers: 0

checkpoint:
  kbest_n: 10
  latest_n: 10

model_type: BertChLinear
model_params: bert-base-uncased
  pretrained_token:
  output_size: 4
  dropout: 0.0
  bert_size: 768

training:
  n_epoch: 100
  lr: !!float 1e-5
  lr_decay: 1.0 
  weight_decay: !!float 1e-06
  global_grad_clip: 5.0
  log_interval: 10
  log_path: log/train0809.log

testing:
  log_path: log/test2011.log


