data:
  dataset_type: Bert
  train_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/bert_zh/train_zh
  dev_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/bert_zh/dev_zh
  test_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/bert_zh/test_valid_zh
  data_params: 
    pretrained_token: bert-base-chinese
    punc_path: /data4/mahaoxin/PaddleSpeechTask/examples/punctuation_restoration/chinese/data/bert_zh/punc_vocab
    seq_len: 100
  batch_size: 8
  sortagrad: True 
  shuffle_method: batch_shuffle
  num_workers: 0

model_type: BertChLinear
model_params:
  output_size: 4
  dropout: 0.0
  bert_size: 768

training:
  n_epoch: 50
  lr: !!float 1e-5
  lr_decay: 1.0 
  weight_decay: !!float 1e-06
  global_grad_clip: 5.0
  log_interval: 10



