# https://yaml.org/type/float.html
data:
  language: chinese
  raw_path: /data4/mahaoxin/PaddleSpeechTask/data/chinese/data1  #path to raw dataset
  raw_train_file: train
  raw_dev_file: dev
  raw_test_file: test
  vocab_file: vocab_char_fre
  punc_file: punc_vocab 
  save_path: data/data1  #path to save dataset
  seq_len: 100
  batch_size: 32
  sortagrad: True 
  shuffle_method: batch_shuffle
  num_workers: 0

model_type: lstm
model_params:
  vocab_size: 4231
  hidden_size: 256
  punc_size: 6
  num_layers: 2
  init_scale: 0.1
  dropout: 0.0

training:
  n_epoch: 24
  lr: !!float 1e-4
  lr_decay: 1.0 
  weight_decay: !!float 1e-06
  global_grad_clip: 5.0
  log_interval: 1
